-- Complete merchants seed data (63 merchants)
-- Run this after migrations have been applied

DELETE FROM merchants;

INSERT INTO merchants (id, canonical_name, aliases, primary_category, secondary_categories, mcc_codes, is_online_only, notes) VALUES
('whole_foods_market', 'Whole Foods Market', ARRAY['Whole Foods', 'WFM', 'WHOLEFDS', 'Whole Foods Market Inc'], 'GROCERY', ARRAY[]::text[], ARRAY['5411'], false, 'Premium grocery chain, owned by Amazon. Often included in Chase Freedom/Flex rotating categories.'),
('kroger', 'Kroger', ARRAY['Kroger Co', 'Ralphs', 'Fred Meyer', 'QFC', 'Smith''s', 'Fry''s', 'King Soopers', 'Mariano''s', 'Dillons', 'Gerbes', 'KROGR'], 'GROCERY', ARRAY[]::text[], ARRAY['5411'], false, NULL),
('trader_joes', 'Trader Joe''s', ARRAY['Trader Joes', 'TJ''s', 'TRADERJOES'], 'GROCERY', ARRAY[]::text[], ARRAY['5411'], false, NULL),
('aldi', 'Aldi', ARRAY['Aldi Süd', 'Aldi Nord', 'ALDI US'], 'GROCERY', ARRAY[]::text[], ARRAY['5411'], false, NULL),
('costco', 'Costco', ARRAY['Costco Warehouse', 'Costco.com', 'COSTCO'], 'WHOLESALE_CLUBS', ARRAY[]::text[], ARRAY['5411', '5942'], false, 'Warehouse club. Explicitly EXCLUDED from Amex Gold 4x grocery earn.'),
('sams_club', 'Sam''s Club', ARRAY['Sams Club', 'Sam''s Warehouse Club', 'SAMSCLUB'], 'WHOLESALE_CLUBS', ARRAY[]::text[], ARRAY['5411', '5942'], false, 'Warehouse club. Explicitly EXCLUDED from Amex Gold 4x grocery earn.'),
('target', 'Target', ARRAY['Target Corp', 'Target Stores', 'Target.com', 'TARGET'], 'GROCERY', ARRAY['GENERAL'], ARRAY['5411', '5399'], false, 'Super-target format has grocery. Online also available.'),
('walmart', 'Walmart', ARRAY['Walmart Inc', 'Walmart Stores', 'Walmart.com', 'WALMART', 'Walmart Supercenter'], 'GROCERY', ARRAY['GENERAL'], ARRAY['5411', '5399'], false, 'Supercenter format includes grocery. Note: Some cards exclude superstores from grocery earn.'),
('publix', 'Publix', ARRAY['Publix Super Market', 'Publix Markets', 'PUBLIX'], 'GROCERY', ARRAY[]::text[], ARRAY['5411'], false, 'Regional chain in southeastern US.'),
('heb', 'H-E-B', ARRAY['HEB', 'H.E.B', 'H-E-B Grocery Company'], 'GROCERY', ARRAY[]::text[], ARRAY['5411'], false, 'Regional chain in Texas.'),
('wegmans', 'Wegmans', ARRAY['Wegmans Food Markets', 'WEGMANS'], 'GROCERY', ARRAY[]::text[], ARRAY['5411'], false, NULL),
('meijer', 'Meijer', ARRAY['Meijer Inc', 'MEIJER'], 'GROCERY', ARRAY['GENERAL'], ARRAY['5411', '5399'], false, 'Regional chain in Midwest. Superstore format.'),
('stop_and_shop', 'Stop & Shop', ARRAY['Stop and Shop', 'STOPNSHOP'], 'GROCERY', ARRAY[]::text[], ARRAY['5411'], false, NULL),
('giant_food', 'Giant Food', ARRAY['Giant Food Stores', 'GIANT'], 'GROCERY', ARRAY[]::text[], ARRAY['5411'], false, NULL),
('shoprite', 'ShopRite', ARRAY['Shop Rite', 'Wakefern', 'SHOPRITE'], 'GROCERY', ARRAY[]::text[], ARRAY['5411'], false, NULL),
('mcdonalds', 'McDonald''s', ARRAY['McDonalds', 'McDonald''s Corp', 'MCD', 'MCDONALDS'], 'DINING', ARRAY[]::text[], ARRAY['5814'], false, NULL),
('starbucks', 'Starbucks', ARRAY['Starbucks Coffee', 'Starbucks Inc', 'SBUX', 'STARBUCKS'], 'DINING', ARRAY[]::text[], ARRAY['5814', '5499'], false, NULL),
('chipotle', 'Chipotle Mexican Grill', ARRAY['Chipotle', 'CMG', 'CHIPOTLE'], 'DINING', ARRAY[]::text[], ARRAY['5814'], false, NULL),
('subway', 'Subway', ARRAY['Subway Inc', 'Subway Restaurant', 'SUBWAY'], 'DINING', ARRAY[]::text[], ARRAY['5814'], false, NULL),
('dominos', 'Domino''s Pizza', ARRAY['Dominos', 'Domino''s Inc', 'DOMINOS'], 'DINING', ARRAY[]::text[], ARRAY['5814'], false, NULL),
('pizza_hut', 'Pizza Hut', ARRAY['Pizza Hut Inc', 'PIZZAHUT'], 'DINING', ARRAY[]::text[], ARRAY['5814'], false, NULL),
('taco_bell', 'Taco Bell', ARRAY['Taco Bell Corp', 'TACOBELL'], 'DINING', ARRAY[]::text[], ARRAY['5814'], false, NULL),
('wendys', 'Wendy''s', ARRAY['Wendy''s Co', 'WENDYS'], 'DINING', ARRAY[]::text[], ARRAY['5814'], false, NULL),
('burger_king', 'Burger King', ARRAY['Burger King Corp', 'BURGERKING'], 'DINING', ARRAY[]::text[], ARRAY['5814'], false, NULL),
('panera_bread', 'Panera Bread', ARRAY['Panera Co', 'PANERA'], 'DINING', ARRAY[]::text[], ARRAY['5814'], false, NULL),
('chick_fil_a', 'Chick-fil-A', ARRAY['Chick-fil-A Inc', 'Chick fil A', 'CFA', 'CHICKFILA'], 'DINING', ARRAY[]::text[], ARRAY['5814'], false, NULL),
('dunkin', 'Dunkin''', ARRAY['Dunkin Donuts', 'Dunkin Brands', 'DUNKIN'], 'DINING', ARRAY[]::text[], ARRAY['5814'], false, NULL),
('kfc', 'KFC', ARRAY['Kentucky Fried Chicken', 'KFC Corp', 'KENTUCKY FRIED CHICKEN'], 'DINING', ARRAY[]::text[], ARRAY['5814'], false, NULL),
('popeyes', 'Popeyes Louisiana Kitchen', ARRAY['Popeyes', 'POPEYES'], 'DINING', ARRAY[]::text[], ARRAY['5814'], false, NULL),
('five_guys', 'Five Guys', ARRAY['Five Guys Burgers', 'FIVEGUYS'], 'DINING', ARRAY[]::text[], ARRAY['5814'], false, NULL),
('shake_shack', 'Shake Shack', ARRAY['Shake Shack Inc', 'SHAKESHACK'], 'DINING', ARRAY[]::text[], ARRAY['5814'], false, NULL),
('in_n_out', 'In-N-Out Burger', ARRAY['In and Out', 'In N Out', 'INNOUT'], 'DINING', ARRAY[]::text[], ARRAY['5814'], false, 'Regional chain, primarily West Coast.'),
('olive_garden', 'Olive Garden', ARRAY['Olive Garden Italian', 'OLIVEGARDEN'], 'DINING', ARRAY[]::text[], ARRAY['5812'], false, NULL),
('red_lobster', 'Red Lobster', ARRAY['Red Lobster Inc', 'REDLOBSTER'], 'DINING', ARRAY[]::text[], ARRAY['5812'], false, NULL),
('applebees', 'Applebee''s', ARRAY['Applebees Bar and Grill', 'APPLEBEES'], 'DINING', ARRAY[]::text[], ARRAY['5812'], false, NULL),
('buffalo_wild_wings', 'Buffalo Wild Wings', ARRAY['BDubs', 'BWW', 'Buffalo Wings', 'BDUBS'], 'DINING', ARRAY['ENTERTAINMENT'], ARRAY['5812'], false, NULL),
('chilis', 'Chili''s Bar & Grill', ARRAY['Chilis', 'Chillis', 'CHILIS'], 'DINING', ARRAY[]::text[], ARRAY['5812'], false, NULL),
('texas_roadhouse', 'Texas Roadhouse', ARRAY['TEXASROADHOUSE'], 'DINING', ARRAY[]::text[], ARRAY['5812'], false, NULL),
('united_airlines', 'United Airlines', ARRAY['United', 'UAL', 'United Air Lines', 'UNITEDAIR'], 'TRAVEL_AIRLINES', ARRAY['TRAVEL_GENERAL'], ARRAY['4511'], false, NULL),
('delta_airlines', 'Delta Air Lines', ARRAY['Delta', 'DAL', 'DELTAAIR'], 'TRAVEL_AIRLINES', ARRAY['TRAVEL_GENERAL'], ARRAY['4511'], false, NULL),
('american_airlines', 'American Airlines', ARRAY['American', 'AAL', 'American Air Lines', 'AMERICANAIR'], 'TRAVEL_AIRLINES', ARRAY['TRAVEL_GENERAL'], ARRAY['4511'], false, NULL),
('southwest_airlines', 'Southwest Airlines', ARRAY['Southwest', 'SWA', 'SOUTHWEST'], 'TRAVEL_AIRLINES', ARRAY['TRAVEL_GENERAL'], ARRAY['4511'], false, NULL),
('marriott', 'Marriott International', ARRAY['Marriott Hotels', 'Marriott Bonvoy', 'MARRIOTT'], 'TRAVEL_HOTELS', ARRAY['TRAVEL_GENERAL'], ARRAY['7011'], false, NULL),
('hilton', 'Hilton Hotels', ARRAY['Hilton', 'Hilton Honors', 'HILTON'], 'TRAVEL_HOTELS', ARRAY['TRAVEL_GENERAL'], ARRAY['7011'], false, NULL),
('hyatt', 'Hyatt Hotels', ARRAY['Hyatt', 'Hyatt Corp', 'HYATT'], 'TRAVEL_HOTELS', ARRAY['TRAVEL_GENERAL'], ARRAY['7011'], false, NULL),
('airbnb', 'Airbnb', ARRAY['Airbnb Inc', 'AIRBNB'], 'TRAVEL_HOTELS', ARRAY['TRAVEL_GENERAL'], ARRAY['7011'], true, NULL),
('booking_com', 'Booking.com', ARRAY['Booking', 'BOOKING'], 'TRAVEL_HOTELS', ARRAY['TRAVEL_GENERAL'], ARRAY['7011'], true, NULL),
('expedia', 'Expedia', ARRAY['Expedia Inc', 'EXPEDIA'], 'TRAVEL_GENERAL', ARRAY['TRAVEL_HOTELS', 'TRAVEL_AIRLINES'], ARRAY['7011'], true, NULL),
('uber', 'Uber', ARRAY['Uber Technologies', 'Uber Rides', 'UBER'], 'TRANSIT', ARRAY[]::text[], ARRAY['4121'], true, NULL),
('lyft', 'Lyft', ARRAY['Lyft Inc', 'LYFT'], 'TRANSIT', ARRAY[]::text[], ARRAY['4121'], true, NULL),
('netflix', 'Netflix', ARRAY['Netflix Inc', 'NETFLIX'], 'STREAMING', ARRAY[]::text[], ARRAY['4999'], true, NULL),
('hulu', 'Hulu', ARRAY['Hulu LLC', 'HULU'], 'STREAMING', ARRAY[]::text[], ARRAY['4999'], true, NULL),
('disney_plus', 'Disney+', ARRAY['Disney Plus', 'Disney Plus Video Service', 'DISNEYPLUS'], 'STREAMING', ARRAY[]::text[], ARRAY['4999'], true, NULL),
('spotify', 'Spotify', ARRAY['Spotify AB', 'SPOTIFY'], 'STREAMING', ARRAY[]::text[], ARRAY['4999'], true, NULL),
('apple_tv_plus', 'Apple TV+', ARRAY['Apple TV Plus', 'Apple Music Subscription', 'APPLETV'], 'STREAMING', ARRAY[]::text[], ARRAY['4999'], true, NULL),
('cvs', 'CVS Pharmacy', ARRAY['CVS', 'CVS Health', 'CVSPHARMACY'], 'DRUGSTORES', ARRAY[]::text[], ARRAY['5912'], false, NULL),
('walgreens', 'Walgreens', ARRAY['Walgreens Boots Alliance', 'WALGREENS'], 'DRUGSTORES', ARRAY[]::text[], ARRAY['5912'], false, 'Named in Amex merchant guidance for additional rewards.'),
('rite_aid', 'Rite Aid', ARRAY['Rite Aid Corp', 'RITEAID'], 'DRUGSTORES', ARRAY[]::text[], ARRAY['5912'], false, NULL),
('shell_gas', 'Shell Gas Station', ARRAY['Shell', 'Shell Oil', 'SHELL'], 'GAS_STATIONS', ARRAY[]::text[], ARRAY['5541'], false, NULL),
('bp_gas', 'BP Gas Station', ARRAY['BP', 'British Petroleum', 'BP Amoco', 'BP STATION'], 'GAS_STATIONS', ARRAY[]::text[], ARRAY['5541'], false, NULL),
('chevron', 'Chevron', ARRAY['Chevron Corp', 'CHEVRON'], 'GAS_STATIONS', ARRAY[]::text[], ARRAY['5541'], false, NULL),
('exxon_mobil', 'ExxonMobil', ARRAY['Exxon', 'Mobil', 'EXXON'], 'GAS_STATIONS', ARRAY[]::text[], ARRAY['5541'], false, NULL),
('amazon', 'Amazon', ARRAY['Amazon.com', 'Amazon Inc', 'AMAZON'], 'GENERAL', ARRAY[]::text[], ARRAY['5411', '5999', '5942'], true, 'Typically included in Chase Freedom quarterly categories.'),
('best_buy', 'Best Buy', ARRAY['Best Buy Co', 'BESTBUY'], 'GENERAL', ARRAY[]::text[], ARRAY['5731'], false, NULL),
('home_depot', 'The Home Depot', ARRAY['Home Depot', 'HD', 'HOMEDEPOT'], 'HOME_IMPROVEMENT', ARRAY[]::text[], ARRAY['5211'], false, NULL),
('lowes', 'Lowe''s', ARRAY['Lowes Home Improvement', 'Lowes Co', 'LOWES'], 'HOME_IMPROVEMENT', ARRAY[]::text[], ARRAY['5211'], false, NULL),
('amc_theaters', 'AMC Theaters', ARRAY['AMC Entertainment', 'AMC', 'AMCTHEATRES'], 'ENTERTAINMENT', ARRAY[]::text[], ARRAY['7832'], false, NULL),
('regal_cinemas', 'Regal Cinemas', ARRAY['Regal Entertainment', 'Regal Movies', 'REGAL'], 'ENTERTAINMENT', ARRAY[]::text[], ARRAY['7832'], false, NULL),
('ticketmaster', 'Ticketmaster', ARRAY['Ticketmaster Entertainment', 'TICKETMASTER'], 'ENTERTAINMENT', ARRAY[]::text[], ARRAY['7922'], true, NULL),
-- Department Stores & Apparel
('nordstrom', 'Nordstrom', ARRAY['Nordstrom Inc', 'Nordstrom Rack', 'NORDSTROM'], 'DEPARTMENT_STORES', ARRAY[]::text[], ARRAY['5311'], false, NULL),
('macys', 'Macy''s', ARRAY['Macys', 'Macy''s Inc', 'MACYS'], 'DEPARTMENT_STORES', ARRAY[]::text[], ARRAY['5311'], false, NULL),
('bloomingdales', 'Bloomingdale''s', ARRAY['Bloomingdales', 'BLOOMINGDALES'], 'DEPARTMENT_STORES', ARRAY[]::text[], ARRAY['5311'], false, NULL),
('neiman_marcus', 'Neiman Marcus', ARRAY['Neiman Marcus Group', 'NEIMANMARCUS'], 'DEPARTMENT_STORES', ARRAY[]::text[], ARRAY['5311'], false, NULL),
('saks_fifth_avenue', 'Saks Fifth Avenue', ARRAY['Saks', 'Saks Inc', 'SAKS'], 'DEPARTMENT_STORES', ARRAY[]::text[], ARRAY['5311'], false, NULL),
-- Apparel / Clothing Brands
('zara', 'Zara', ARRAY['Zara USA', 'Inditex', 'ZARA'], 'DEPARTMENT_STORES', ARRAY[]::text[], ARRAY['5699'], false, NULL),
('lululemon', 'Lululemon', ARRAY['lululemon athletica', 'Lululemon Inc', 'LULULEMON'], 'DEPARTMENT_STORES', ARRAY[]::text[], ARRAY['5699'], false, NULL),
('hm', 'H&M', ARRAY['H and M', 'H&M Group', 'HM'], 'DEPARTMENT_STORES', ARRAY[]::text[], ARRAY['5651'], false, NULL),
('gap', 'Gap', ARRAY['Gap Inc', 'Gap Stores', 'GAP'], 'DEPARTMENT_STORES', ARRAY[]::text[], ARRAY['5651'], false, NULL),
('old_navy', 'Old Navy', ARRAY['Old Navy LLC', 'OLDNAVY'], 'DEPARTMENT_STORES', ARRAY[]::text[], ARRAY['5651'], false, NULL),
('banana_republic', 'Banana Republic', ARRAY['Banana Republic LLC', 'BANANAREPUBLIC'], 'DEPARTMENT_STORES', ARRAY[]::text[], ARRAY['5651'], false, NULL),
('uniqlo', 'Uniqlo', ARRAY['UNIQLO Co', 'Fast Retailing', 'UNIQLO'], 'DEPARTMENT_STORES', ARRAY[]::text[], ARRAY['5651'], false, NULL),
('forever_21', 'Forever 21', ARRAY['Forever21', 'FOREVER21'], 'DEPARTMENT_STORES', ARRAY[]::text[], ARRAY['5651'], false, NULL),
('urban_outfitters', 'Urban Outfitters', ARRAY['Urban Outfitters Inc', 'URBANOUTFITTERS', 'UO'], 'DEPARTMENT_STORES', ARRAY[]::text[], ARRAY['5699'], false, NULL),
('anthropologie', 'Anthropologie', ARRAY['Anthropologie Group', 'ANTHROPOLOGIE'], 'DEPARTMENT_STORES', ARRAY[]::text[], ARRAY['5699'], false, NULL),
('free_people', 'Free People', ARRAY['Free People LLC', 'FREEPEOPLE', 'FP'], 'DEPARTMENT_STORES', ARRAY[]::text[], ARRAY['5699'], false, NULL),
('express', 'Express', ARRAY['Express Inc', 'EXPRESS'], 'DEPARTMENT_STORES', ARRAY[]::text[], ARRAY['5651'], false, NULL),
('tj_maxx', 'TJ Maxx', ARRAY['TJX', 'TJ Maxx Inc', 'T.J.Maxx', 'TJMAXX'], 'DEPARTMENT_STORES', ARRAY[]::text[], ARRAY['5651'], false, NULL),
('marshalls', 'Marshalls', ARRAY['Marshalls Inc', 'MARSHALLS'], 'DEPARTMENT_STORES', ARRAY[]::text[], ARRAY['5651'], false, NULL),
('ross', 'Ross Dress for Less', ARRAY['Ross Stores', 'Ross', 'ROSS'], 'DEPARTMENT_STORES', ARRAY[]::text[], ARRAY['5651'], false, NULL),
('nike', 'Nike', ARRAY['Nike Inc', 'Nike Store', 'Nike.com', 'NIKE'], 'DEPARTMENT_STORES', ARRAY[]::text[], ARRAY['5699'], false, NULL),
('adidas', 'Adidas', ARRAY['Adidas AG', 'Adidas Store', 'Adidas.com', 'ADIDAS'], 'DEPARTMENT_STORES', ARRAY[]::text[], ARRAY['5699'], false, NULL),
('foot_locker', 'Foot Locker', ARRAY['Foot Locker Inc', 'FOOTLOCKER'], 'DEPARTMENT_STORES', ARRAY[]::text[], ARRAY['5661'], false, NULL),
('dsw', 'DSW', ARRAY['Designer Shoe Warehouse', 'DSW Inc', 'DSW Shoes'], 'DEPARTMENT_STORES', ARRAY[]::text[], ARRAY['5661'], false, NULL),
('shein', 'SHEIN', ARRAY['Shein Group', 'SHEIN.com'], 'DEPARTMENT_STORES', ARRAY[]::text[], ARRAY['5699'], true, NULL),
('asos', 'ASOS', ARRAY['ASOS.com', 'ASOS plc'], 'DEPARTMENT_STORES', ARRAY[]::text[], ARRAY['5699'], true, NULL),
-- Phone / Wireless
('verizon', 'Verizon', ARRAY['Verizon Wireless', 'Verizon Communications', 'VERIZON'], 'PHONE_WIRELESS', ARRAY[]::text[], ARRAY['4814'], false, NULL),
('att', 'AT&T', ARRAY['AT&T Inc', 'AT and T', 'ATT'], 'PHONE_WIRELESS', ARRAY[]::text[], ARRAY['4814'], false, NULL),
('tmobile', 'T-Mobile', ARRAY['T Mobile', 'T-Mobile USA', 'TMOBILE'], 'PHONE_WIRELESS', ARRAY[]::text[], ARRAY['4814'], false, NULL);
